on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.tf'
    # Sequence of patterns matched against refs/tags
    #tags:
    #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest release
        run: |
          echo "latest_release=$(curl -silent https://api.github.com/repos/terraform-azurerm-modules/terraform-azurerm-azopsreference/releases/latest | jq -r .tag_name | sed s/v// )" >> $GITHUB_ENV
      - name: Increment semver
        id: semver
        uses: matt-FFFFFF/simple-semver
        with:
          semver_input: ${{ latest_release }}
          increment: i
      - name: Display new semver
        run: echo ${{ steps.semver.outputs.semver }}
      - name: Create basic CHANGELOG
        run: echo $(git log -1 --oneline) >CHANGELOG.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
