name: 'Update from upstream'

on:
  workflow_dispatch:

env:
  GH_CLI_VER: 0.11.1
  GIT_USER_NAME: System
  GIT_USER_EMAIL: noreply@azure.com

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout upstream
      uses: actions/checkout@v2.3.1
      with:
        repository: Azure/Enterprise-Scale
        path: es

    - name: Checkout module
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: true
        path: module

    - name: Display env
      run: |
        env | sort

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.1.0
    
    - name: Download jq 1.6
      run: |
        curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o $HOME/jq
        sudo cp -fv $HOME/jq /usr/bin
        sudo chmod a+x /usr/bin/jq
        rm $HOME/jq

    - name: Create branch
      run: |
        git checkout -b autoupdate
        git reset --hard origin/main
      working-directory: ${{ github.workspace }}/module
      
    - name: Convert AzOpsReference
      run: |
        jq --version
        $GITHUB_WORKSPACE/module/scripts/convertazopsreference.sh -r "$GITHUB_WORKSPACE/es/azopsreference" -o "$GITHUB_WORKSPACE/module"
    
    - name: Add changes & create PR
      run: |
        if [ "$(git status -s)" ]; then
          git config --global user.name $GIT_USER_NAME
          git config --global user.email $GIT_USER_EMAIL
          git add *.tf
          git commit -m 'Updated from upstream'
          git push --force -u origin autoupdate
          gh pr create --title "Autoupdate from upstream" --body "Auto-generated PR" --label "system"
        fi
      working-directory: ${{ github.workspace }}/module
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          